#:kivy 1.10.0

<ScreenTwo>:
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: 'This is SCREEN TWO'
        BoxLayout:
            orientation: 'horizontal'
            Button:
                text: "Go to Screen 1"
                on_press: root.manager.current = 'ScreenWelcome'
            Button:
                text: "Go to Home"
                on_press: root.manager.current = 'ScreenMain'
