#:kivy 1.10.0

<ScreenOne>:
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: 'This is SCREEN ONE'
        BoxLayout:
            orientation: 'horizontal'
            Button:
                text: "Go to Screen 2"
                on_press: root.manager.current = 'Screen2'
            Button:
                text: "Back to Home"
                on_press: root.manager.current = 'ScreenMain'
